repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3.7
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.5.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3.7
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "sourmash:."]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.15
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: 'tests/test-data'
    -   id: end-of-file-fixer
        exclude: 'tests/test-data'
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 18.8.0"]
        language_version: python3.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.12.0
    hooks:
    -   id: pyupgrade
